version: "3.8"
services:
  grafana:
    image: grafana/grafana:9.3.6
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - jmeter-influxdb-grafana

  influxdb:
    image: influxdb:1.4
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - jmeter-influxdb-grafana

volumes:
  grafana:
  influxdb:
networks:
  jmeter-influxdb-grafana:
